# cluster_config.yml - cluster configuration
# submit as: 
# snakemake --cluster "sbatch -A {cluster.account} -t {cluster.time} -p {cluster.partition} -n {cluster.nodes} -J {cluster.name}" --cluster-config cluster_config.yml --jobs 3 

__default__:
    account: snic2021-22-59
    partition: core
    time: 08:00:00
    nodes: 4  
    name: scATAC_pipeline
    email: alva.annett.4036@student.uu.se
